### ISSUE TITLE
Error importing symbolic_alchemy

### ISSUE THREAD

**Issue by SimonOuellette35** [deepmind/dm_alchemy#10]
After following the installation steps, I run into an error when I merely import symbolic_alchemy:

`import dm_alchemy`
`from dm_alchemy import symbolic_alchemy`

I get the following error:

> Traceback (most recent call last):
>   File "trainAlchemy.py", line 2, in <module>
>     from dm_alchemy import symbolic_alchemy
>   File "lib/python3.11/site-packages/dm_alchemy/symbolic_alchemy.py", line 23, in <module>
>     from dm_alchemy import event_tracker
>   File "lib/python3.11/site-packages/dm_alchemy/event_tracker.py", line 27, in <module>
>     from dm_alchemy.types import utils
>   File "lib/python3.11/site-packages/dm_alchemy/types/utils.py", line 126, in <module>
>     @dataclasses.dataclass
>      ^^^^^^^^^^^^^^^^^^^^^
>   File "lib/python3.11/dataclasses.py", line 1221, in dataclass
>     return wrap(cls)
>            ^^^^^^^^^
>   File "lib/python3.11/dataclasses.py", line 1211, in wrap
>     return _process_class(cls, init, repr, eq, order, unsafe_hash,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "lib/python3.11/dataclasses.py", line 959, in _process_class
>     cls_fields.append(_get_field(cls, name, type, kw_only))
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "lib/python3.11/dataclasses.py", line 816, in _get_field
>     raise ValueError(f'mutable default {type(f.default)} for field '
> ValueError: mutable default <class 'dm_alchemy.types.utils.SymbolicBot'> for field ideal_observer is not allowed: use default_factory
> 

Any thoughts on what could cause this?

**Comment by SimonOuellette35** [comment]
That does fix the error, thank you for the quick response.
